In [1]:
!python --version

Python 3.12.7

In [2]:
import pandas as pd
import os

folder_path = r"C:\Users\Jeen priyee\Downloads\gda_till_march2026"

# pick all Excel files
all_files = [f for f in os.listdir(folder_path) if f.lower().endswith(".xlsx")]

print("Excel files found:", len(all_files))

if not all_files:
    raise ValueError("No Excel files found in the folder.")

df_list = []

print("\nRows per Excel file (before merging):")

for file in all_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_excel(file_path)

    # row count before merge
    print(f"{file}: {df.shape[0]} rows")

    df_list.append(df)

Excel files found: 11

Rows per Excel file (before merging):
22-11-2020 to 31-03-2021(2).xlsx: 11374 rows
31-01-2023 to 31-05-2023(7).xlsx: 7176 rows
31-03-2021 to 31-10-2021(3).xlsx: 9877 rows
31-03-2022 to 31-08-2022(5).xlsx: 10803 rows
31-05-2023 to 31-12-2023(8).xlsx: 10104 rows
31-08-2022 to 31-01-2023(6).xlsx: 6858 rows
31-10-2021 to 31-03-2022(4).xlsx: 12016 rows
31-10-2025 to 31-03-2026(11).xlsx: 6331 rows
31-12-2023 to 31-12-2024(9).xlsx: 10180 rows
31-12-2024 to 31-10-2025(10).xlsx: 10966 rows
start to 22-11-2020(1).xlsx: 9712 rows

In [3]:
import pandas as pd
import os

folder_path = r"C:\Users\Jeen priyee\Downloads\gda_till_march2026"

# pick all Excel files
all_files = [f for f in os.listdir(folder_path) if f.lower().endswith(".xlsx")]

print("Excel files found:", len(all_files))

if not all_files:
    raise ValueError("No Excel files found in the folder.")

df_list = []

for file in all_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_excel(file_path)
    df_list.append(df)

merged_df = pd.concat(df_list, ignore_index=True)

# save as CSV
output_path = os.path.join(folder_path, "gda_updated_31-03-2026.csv")
merged_df.to_csv(output_path, index=False, encoding="utf-8")

print("Merging complete!")
print("Final rows, columns:", merged_df.shape)

Excel files found: 11
Merging complete!
Final rows, columns: (105397, 29)

In [4]:
import pandas as pd

gda_updated = pd.read_csv(r"C:\Users\Jeen priyee\Downloads\gda_till_march2026\gda_updated_31-03-2026.csv")
gda_updated.head()

,S No,Compliant ID,Offences,Date and Time,Geo Location,Address,Latitude & Longitude,Department Name,Assigned User Name,Assigned User ID,...,State,Status,User Feedback,Date & Time of Resolution,Officer Comment,Reopen By Citizen,Reopen By Green Delhi,Resolve Image,Offence Image,Total Action Taken
0,1,20743,Illegal dumping of Garbage on road sides/ vaca...,2021-03-31 23:39:00,"102/415, Shiv Nagar, Janakpuri, New Delhi, Del...","102/430A, Pocket 5, Shiv Nagar, Janakpuri, New...","28.6296378, 77.0963926",Municipal Corporation of Delhi (MCD),Mukesh Kumar ASI 15-S,15-S,...,DL,Resolved,NaN,2021-04-03 00:43:05,resolve,NaN,NaN,https://greendelhi.nic.in/storage/resolved_ima...,https://greendelhi.nic.in/storage/photo/X1qVGX...,NaN
1,2,20742,Dumping of Construction & Demolition Waste,2021-03-31 18:47:00,"524/1, PVC Markat Rd, Tikri Kalan, Delhi, 1100...","524/1, PVC Markat Rd, Tikri Kalan, Delhi, 1100...","28.6819323, 76.9660785",Public Works Department (PWD),J. C. Singh AE WR-22,aewr2sd22pwd,...,DL,Resolved,NaN,2021-04-13 17:14:14,Malba lifted,NaN,NaN,https://greendelhi.nic.in/storage/resolved_ima...,https://greendelhi.nic.in/storage/photo/diEZgv...,NaN
2,3,20741,Dust Pollution due to Construction/ Demolition...,2021-03-31 18:26:00,"EA-28 Ground Floor, Sant Kabir Nagar, Block F,...","EA-28 Ground Floor, Sant Kabir Nagar, Block F,...","28.6291315, 77.1471017",Municipal Corporation of Delhi (MCD),Vipin Mann,vipinmannclz,...,DL,Resolved,NaN,2026-01-09 12:07:13,resolved,NaN,NaN,https://greendelhi.nic.in/storage/photo/2qAwVV...,https://greendelhi.nic.in/storage/photo/nPfBN9...,NaN
3,4,20740,Dumping of Construction & Demolition Waste,2021-03-31 18:13:00,"15, MCE Force Colony, Block A, Saket, New Delh...","15, MCE Force Colony, Block A, Saket, New Delh...","28.5274928, 77.2043506",Municipal Corporation of Delhi (MCD),SI 67-S/SZ Raghuraj,sisouth67s,...,DL,Resolved,NaN,2021-04-05 12:35:31,Garbage removed,NaN,NaN,https://greendelhi.nic.in/storage/resolved_ima...,https://greendelhi.nic.in/storage/photo/Da7vrB...,NaN
4,5,20739,Burning of garbage/plastic waste,2021-03-31 18:12:00,"Rajeev Nagar (Signature Bridge), Usmanpur, Sha...","C-1141, C-1141, Gali Number 19, Shri Ram Colon...","28.7074882, 77.251413",Municipal Corporation of Delhi (MCD),RISHI PAL ASI/64-E,si64e,...,DL,Resolved,NaN,2021-04-05 12:29:49,work has been done.,NaN,NaN,https://greendelhi.nic.in/storage/resolved_ima...,https://greendelhi.nic.in/storage/photo/f9EPTw...,NaN

In [5]:
gda_updated = gda_updated.sort_values(by="Compliant ID", ascending=False)

In [6]:
gda_updated.head()

,S No,Compliant ID,Offences,Date and Time,Geo Location,Address,Latitude & Longitude,Department Name,Assigned User Name,Assigned User ID,...,State,Status,User Feedback,Date & Time of Resolution,Officer Comment,Reopen By Citizen,Reopen By Green Delhi,Resolve Image,Offence Image,Total Action Taken
41158,1929,11111111,Illegal dumping of Garbage on road sides/ vaca...,2023-06-27 08:34:00,"G-21, SSG Majesty mall, Guru Harkishan Marg, M...","Mamram Majesty Mall, Road No.43, 220, Guru Har...","28.6888628, 77.1075475",Development Department of Delhi,"Sonu Kumar, ASI W. No. 201 (Lalita Park)",asi201mcd,...,DL,Resolved,where all the supporrtive greviance sytem was ...,2023-07-20 17:58:28,Clean,NaN,NaN,https://greendelhi.nic.in/storage/photo/Ap4IVY...,https://greendelhi.nic.in/storage/photo/fK5q0L...,NaN
41157,1928,2222222,Illegal dumping of Garbage on road sides/ vaca...,2023-06-27 08:34:00,"G-21, SSG Majesty mall, Guru Harkishan Marg, M...","Mamram Majesty Mall, Road No.43, 220, Guru Har...","28.6888628, 77.1075475",Municipal Corporation of Delhi (MCD),Narender 58 kpz,narender58,...,DL,Unrelated,NaN,2026-03-05 12:17:29,This plot is DDA land. Hence the complaint se...,NaN,NaN,https://greendelhi.nic.in/storage/photo/Ap4IVY...,https://greendelhi.nic.in/storage/photo/fK5q0L...,NaN
73238,5031,104362,Illegal dumping of Garbage on road sides/ vaca...,2026-03-31 20:46:00,"J9/6, Rajouri Gdn Ext Rd, Block J, Rajouri Gar...","J-9/2, School, opposite SARASWATI BAL MANDIR, ...","28.6433133, 77.1159083",Public Works Department (PWD),NaN,NaN,...,DL,Pending,NaN,NaN,NaN,NaN,NaN,NaN,https://greendelhi.nic.in/storage/photo/T21BNf...,NaN
73239,5032,104361,Illegal dumping of Garbage on road sides/ vaca...,2026-03-31 17:03:00,"J2GW+3CR, Nawada Majra Village, Nawada, Delhi,...","J2GW+3CR, Nawada Majra Village, Nawada, Delhi,...","28.6252073, 77.0460227",Municipal Corporation of Delhi (MCD),Nodal Officer Sh. Akhilesh Kumar,NOMCD,...,DL,Pending,NaN,NaN,NaN,NaN,NaN,NaN,https://greendelhi.nic.in/storage/photo/5SonaZ...,NaN
73240,5033,104360,Potholes on Roads,2026-03-31 14:46:00,"Green View Apartment, 3A, MS Block, Nanak Pura...","Green View Apartment, 3A, MS Block, Nanak Pura...","28.6234064, 77.1165392",Public Works Department (PWD),NaN,NaN,...,DL,Pending,NaN,NaN,NaN,NaN,NaN,NaN,https://greendelhi.nic.in/storage/photo/LsdxvV...,NaN

In [7]:
ids_to_delete = [11111111, 2222222]

# Filter the DataFrame to exclude these IDs
gda_updated = gda_updated[~gda_updated['Compliant ID'].isin(ids_to_delete)]

# Check the updated DataFrame
print(gda_updated)

        S No  Compliant ID                                           Offences  \
73238   5031        104362  Illegal dumping of Garbage on road sides/ vaca...
73239   5032        104361  Illegal dumping of Garbage on road sides/ vaca...
73240   5033        104360                                  Potholes on Roads
73241   5034        104359                                  Potholes on Roads
73242   5035        104358                                  Potholes on Roads
...      ...           ...                                                ...
105385  9701             5  Illegal dumping of Garbage on road sides/ vaca...
105386  9702             4  Illegal dumping of Garbage on road sides/ vaca...
105387  9703             3  Illegal dumping of Garbage on road sides/ vaca...
105388  9704             2                    Air Pollution due to industries
105389  9705             1                    Air Pollution due to industries

              Date and Time  \
73238   2026-03-31 20:46:00
73239   2026-03-31 17:03:00
73240   2026-03-31 14:46:00
73241   2026-03-31 13:47:00
73242   2026-03-31 12:37:00
...                     ...
105385  2020-10-14 15:23:00
105386  2020-10-14 14:56:00
105387  2020-10-14 14:09:00
105388  2020-10-14 13:37:00
105389  2020-10-14 13:33:00

                                             Geo Location  \
73238   J9/6, Rajouri Gdn Ext Rd, Block J, Rajouri Gar...
73239   J2GW+3CR, Nawada Majra Village, Nawada, Delhi,...
73240   Green View Apartment, 3A, MS Block, Nanak Pura...
73241   No.42, 244, Block B2, Shiv Nagar, Janakpuri, D...
73242   111-A, Hari Enclave, Hari Nagar, New Delhi, De...
...                                                   ...
105385  B-247, Industrial Area Phase I, Block B, Narai...
105386  B-235, Loha Mandi Marg, Industrial Area Phase ...
105387  B-88, Industrial Area Phase I, Budh Nagar, Ind...
105388  21, Chandni Chowk, New Delhi, Delhi 110006, India
105389  21, Chandni Chowk, New Delhi, Delhi 110006, India

                                                  Address  \
73238   J-9/2, School, opposite SARASWATI BAL MANDIR, ...
73239   J2GW+3CR, Nawada Majra Village, Nawada, Delhi,...
73240   Green View Apartment, 3A, MS Block, Nanak Pura...
73241   245, Block B2, Shiv Nagar, Janakpuri, Delhi, 1...
73242   111-A, Hari Enclave, Hari Nagar, New Delhi, De...
...                                                   ...
105385  B-247, Industrial Area Phase I, Block B, Narai...
105386  B-235, Loha Mandi Marg, Industrial Area Phase ...
105387  B-88, Industrial Area Phase I, New Delhi, Delh...
105388                           Wazirpur industrial area
105389  21, Chandni Chowk, New Delhi, Delhi 110006, India

          Latitude & Longitude                           Department Name  \
73238   28.6433133, 77.1159083             Public Works Department (PWD)
73239   28.6252073, 77.0460227      Municipal Corporation of Delhi (MCD)
73240   28.6234064, 77.1165392             Public Works Department (PWD)
73241   28.6290074, 77.0923735      Municipal Corporation of Delhi (MCD)
73242   28.6276617, 77.1072056      Municipal Corporation of Delhi (MCD)
...                        ...                                       ...
105385  28.6325596, 77.1362928      Municipal Corporation of Delhi (MCD)
105386  28.6322734, 77.1350935      Municipal Corporation of Delhi (MCD)
105387  28.6328956, 77.1340734      Municipal Corporation of Delhi (MCD)
105388  28.6553813, 77.2366148  Delhi Pollution Control Committee (DPCC)
105389  28.6553813, 77.2366148  Delhi Pollution Control Committee (DPCC)

                      Assigned User Name    Assigned User ID  ... State  \
73238                                NaN                 NaN  ...    DL
73239   Nodal Officer Sh. Akhilesh Kumar               NOMCD  ...    DL
73240                                NaN                 NaN  ...    DL
73241                  Yogesh kumarJE100  yogesh.kumar.JE100  ...    DL
73242                  Yogesh kumarJE100  yogesh.kumar.JE100  ...    DL
...                                  ...                 ...  ...   ...
105385                  104 ASI VIJENDER    karolbagh-SI-104  ...    DL
105386                  104 ASI VIJENDER    karolbagh-SI-104  ...    DL
105387                  104 ASI VIJENDER    karolbagh-SI-104  ...    DL
105388                               NaN                 NaN  ...    DL
105389                 Dr Nandita Moitra              ssingh  ...    DL

          Status User Feedback Date & Time of Resolution  \
73238    Pending           NaN                       NaN
73239    Pending           NaN                       NaN
73240    Pending           NaN                       NaN
73241    Pending           NaN                       NaN
73242    Pending           NaN                       NaN
...          ...           ...                       ...
105385  Resolved           NaN       2021-04-23 07:53:36
105386  Resolved           NaN       2020-12-04 17:51:11
105387  Resolved           NaN       2020-11-10 08:44:16
105388  Rejected           NaN       2020-10-21 12:16:25
105389  Rejected           NaN       2020-11-07 14:36:58

                                          Officer Comment Reopen By Citizen  \
73238                                                 NaN               NaN
73239                                                 NaN               NaN
73240                                                 NaN               NaN
73241                                                 NaN               NaN
73242                                                 NaN               NaN
...                                                   ...               ...
105385                      complent resolve b - 247 ph 1               0.0
105386  Resolved the complaint with photo and disposed...               0.0
105387                   open  site Dhalw compant resolve               0.0
105388                                                NaN               0.0
105389                                            testing               0.0

        Reopen By Green Delhi  \
73238                     NaN
73239                     NaN
73240                     NaN
73241                     NaN
73242                     NaN
...                       ...
105385                    0.0
105386                    0.0
105387                    0.0
105388                    0.0
105389                    0.0

                                            Resolve Image  \
73238                                                 NaN
73239                                                 NaN
73240                                                 NaN
73241                                                 NaN
73242                                                 NaN
...                                                   ...
105385  https://greendelhi.nic.in/storage/photo/UCVKfd...
105386  https://greendelhi.nic.in/storage/resolved_ima...
105387  https://greendelhi.nic.in/storage/photo/QWGspg...
105388                                                NaN
105389                                                NaN

                                            Offence Image Total Action Taken
73238   https://greendelhi.nic.in/storage/photo/T21BNf...                NaN
73239   https://greendelhi.nic.in/storage/photo/5SonaZ...                NaN
73240   https://greendelhi.nic.in/storage/photo/LsdxvV...                NaN
73241   https://greendelhi.nic.in/storage/photo/ro3oUV...                NaN
73242   https://greendelhi.nic.in/storage/photo/4jNfGs...                NaN
...                                                   ...                ...
105385  https://greendelhi.nic.in/storage/photo/rKA2oj...               45.0
105386  https://greendelhi.nic.in/storage/photo/0hcafF...               24.0
105387  https://greendelhi.nic.in/storage/photo/U7HZFd...               64.0
105388  https://greendelhi.nic.in/storage/photo/3SYVAE...               42.0
105389  https://greendelhi.nic.in/storage/photo/yhv4NY...               23.0

[105395 rows x 29 columns]

In [8]:
gda_updated.size

3056455

In [9]:
gda_updated.shape

(105395, 29)

In [10]:
gda_updated.loc[:, 'Compliant ID'] = pd.to_numeric(gda_updated['Compliant ID'], errors='coerce')
gda_updated.shape

(105395, 29)

In [11]:
all_ids = set(range(
    int(gda_updated['Compliant ID'].min()),
    int(gda_updated['Compliant ID'].max()) + 1))

present_ids = set(gda_updated['Compliant ID'].dropna().astype(int))

missing_ids = sorted(list(all_ids - present_ids))
missing_ids

[67871, 74993, 74994, 81426, 81503, 81507, 81567, 81568, 81569]

In [ ]:
missing_complaints = pd.DataFrame({
    "Compliant ID": [
        74993, 74994], "Status": ["Unrelated", "Unrelated"]})

gda_march2026 = pd.concat([gda_updated, missing_complaints], ignore_index=True)

In [ ]:
print("Total complaints:", len(gda_march2026))
gda_march2026["Status"].value_counts()

In [ ]:
gda_march2026.shape

In [ ]:
gda_march2026 = gda_march2026.drop_duplicates(subset="Compliant ID", keep="first")
gda_march2026.shape

In [ ]:
gda_march2026['Date and Time'] = pd.to_datetime(gda_march2026['Date and Time'],format='%Y-%m-%d %H:%M:%S',errors='coerce')

gda_march2026['Month'] = gda_march2026['Date and Time'].dt.strftime('%b %Y')

gda_march2026[['Date and Time', 'Month']].head()

In [ ]:
total_complaints = len(gda_march2026)
total_complaints

In [ ]:
print(gda_march2026.columns)

In [ ]:
gda_updated_31march2026= gda_march2026.copy()
gda_updated_31march2026.to_csv(r"C:\Users\Jeen priyee\Downloads\gda_till_march2026\gda_updated_31march2026.csv", index=False)